In [40]:
import pandas as pd
from scipy import stats
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [41]:
df = pd.read_csv('Full_Diab_NDiab.csv')
df

,C006,C008,I00102,J01101,N001,N00101,N011,P00103,P00404,P00610,...,P05401,P058,Q02901,Q03001,Q03002,Q03802,Q046015,Q046017,Q046018,VDF004
0,1.0,81.0,2.0,1.0,3.0,3.0,1.0,75.0,162.0,2.0,...,NaN,5.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,4.0
1,2.0,72.0,2.0,1.0,3.0,3.0,3.0,79.0,161.0,2.0,...,NaN,6.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,3.0
2,2.0,74.0,1.0,1.0,3.0,3.0,4.0,65.0,148.0,2.0,...,NaN,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,5.0
3,1.0,59.0,1.0,1.0,3.0,2.0,2.0,86.0,187.0,1.0,...,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,5.0
4,2.0,94.0,2.0,1.0,3.0,2.0,1.0,62.0,145.0,1.0,...,NaN,NaN,3.0,1.0,2.0,2.0,1.0,1.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84058,1.0,44.0,2.0,2.0,3.0,2.0,3.0,62.0,162.0,1.0,...,NaN,NaN,5.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0
84059,2.0,26.0,2.0,2.0,2.0,2.0,4.0,75.0,150.0,1.0,...,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0
84060,2.0,54.0,2.0,4.0,3.0,2.0,2.0,63.0,168.0,1.0,...,1.0,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0
84061,2.0,32.0,2.0,1.0,2.0,2.0,1.0,87.0,163.0,2.0,...,NaN,6.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0
84062,1.0,54.0,1.0,1.0,3.0,3.0,1.0,89.0,168.0,2.0,...,NaN,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,5.0

In [54]:
cl = ['C008', 'P00103', 'P00404', 'P053']
categories = [9,1,2]
oe = OrdinalEncoder(categories=[categories])
for i in cl :
    print(df[i].unique())

[ 81.  72.  74.  59.  94.  30.  66.  43.  69.  45.  67.  37.  77.  57.
  92.  63.  65.  44.  68.  38.  48.  58.  61.  51.  49.  39.  75.  88.
  35.  54.  50.  41.  76.  47.  83.  71.  73.  78.  85.  60.  56.  42.
  46.  62.  36.  70.  55.  64.  31.  26.  52.  40.  84.  82.  80.  79.
  86.  34.  18.  24.  53.  95.  91.  17.  29.  32.  15.  25.  28.  20.
  27.  16.  33.  89.  99.  87.  93.  22.  21.  23.  98.  19.  90.  97.
  96. 103. 100. 101. 102. 107. 104.]
[ 75.   79.   65.   86.   62.   55.  125.   53.   63.   72.   58.   69.
  60.   56.   85.   67.    nan  78.   73.   95.   70.   59.   76.   57.
 108.   80.  105.   81.   92.   94.   71.   54.  102.5  61.   87.   52.
 103.   38.   64.  124.   90.   45.   82.   83.   66.   74.5 107.  120.
  93.   77.   85.5  51.   84.  116.  106.   68.  102.  114.   98.   74.
 134.   99.  123.   88.   50.   96.   43.  110.   89.  104.  100.  112.
 118.   91.   84.5  48.   47.   46.   49.   40.   69.2  97.   44.  140.
 101.   33.  126.   69.5 132.  122.  131.  142.   30.   41.   42.   61.5
  51.5 172.   49.5 119.   76.5  71.5 111.   39.   73.5  76.8  53.6  86.5
 130.   78.5  73.6 128.   77.7  77.6 105.3 109.  117.   59.9 129.   65.5
  37.  135.   92.3  60.5  73.4  68.5  35.   77.5  92.5  58.2 136.  168.
  72.4  46.5  58.5  56.5  69.7 115.   81.5  95.5  72.5  64.5  83.5  94.5
  53.2  76.2  49.3  58.8  74.6  54.7  69.8  94.6 160.   67.5  54.2  71.7
 113.  155.   74.2 126.7  66.8 150.   83.7 139.  170.  138.  133.   75.5
  74.8  75.2  75.8  85.6  63.5  64.6  74.3  53.4  48.9  63.2 127.   78.6
  78.3  55.4  51.6  62.4  66.5  62.5  54.5  60.8  95.7  71.8  58.7  46.6
 145.   50.4  68.3 180.   36.   32.   53.8  52.3  66.4  64.8  43.6  26.7
  34.   49.9  52.4  53.7  57.9  82.5  60.2  84.4  50.8  63.8  71.2  79.2
  55.5  88.7  48.7  56.6  64.4  31.   68.8 100.6 158.   49.7  57.6  68.7
  47.7  60.3  86.3  59.8  70.2  73.8  78.1  33.5  52.5  86.7  45.2  62.7
  75.7  77.8  71.6  43.3  25.   53.5 107.4 110.2  59.6  58.4  59.7  44.5
  83.6  45.5  57.4  59.5  89.5 123.5  54.6  67.1  58.6  65.2  99.5  48.5
  93.5  53.3  62.2  66.6  82.3 110.6  59.1  82.8 103.7  70.8  67.2  62.3
 115.9  63.6  70.5  57.5  83.9  50.1  64.9  96.5  47.5  44.3  69.9  76.3
  88.5 176.   60.1 148.   42.9 154.  143.  132.1  46.1  52.7  81.1 137.
  87.6  61.9 178.   90.8 146.   40.5  64.3 121.   98.5  59.2  63.7  80.5
  43.2  63.9  46.8  61.6  87.5  48.8  78.7  66.7  79.5  65.9  70.6  80.7
  61.4  54.3  71.1  80.6  60.6 156.   98.7 128.6  67.9  51.1  84.9  39.5
  50.5  59.3  94.4 128.4  41.5  81.4  50.6  67.7  55.8  97.3  71.4  72.3
 157.   62.6  62.8  56.4  84.8  63.4  89.3  70.9  77.3  95.8  57.8  74.1
  72.1  83.4  81.7  57.3  86.6  73.2 111.6  68.4  75.4  54.4  57.7  94.8
  86.9 101.5  99.6  69.1  89.9 109.5  68.9  90.3 152.   82.4  55.7  65.4
  74.4  88.9  69.3  56.7  83.2  80.4  51.2  65.6  82.6 147.   81.3  72.8
 175.   58.9  78.2  76.1 149.   95.1  49.8  62.9  61.1 141.  190.   89.8
  75.6  89.4  96.9  84.3  46.3  80.3  54.9  72.2  67.8 108.5  81.9  89.7
  86.8  38.4  70.4 159.   76.9  91.5  51.8 101.2  52.8]
[162. 161. 148. 187. 145. 175. 163. 155. 158. 146. 151. 160. 157. 166.
 159. 180. 167. 170. 164. 173. 171. 165. 153. 141. 192. 178. 179. 174.
 150. 169. 154. 156. 143. 149. 168. 172. 176. 140. 144. 177. 152. 186.
 183. 181. 142. 130. 185. 182. 147. 139.  nan 135. 184. 132. 195. 134.
 193. 190. 188. 191. 136. 189. 138. 137. 196. 200. 198. 197. 194. 133.
 128. 199. 202. 201. 129. 206. 204.]
[14. 17. 32. nan  8. 18. 15. 20. 19. 11. 16. 30. 12. 13. 66. 23. 10. 25.
 40. 22.  4.  7. 64. 21. 35. 27. 26. 37.  9.  5. 44. 24. 55. 60. 50. 52.
 38. 29. 36. 70. 28. 53.  6. 41. 47. 42. 45. 48. 67. 68. 39. 34. 61. 33.
 46. 31. 58. 54. 51.  3. 56. 62. 74. 49. 43. 57. 59. 65. 90. 69. 63. 75.
  2. 72.]