In [1]:
import pandas as pd
from scipy import stats
from sklearn.impute import KNNImputer

In [2]:
#Ler Base
df = pd.read_csv("pns2019.csv")
#Array de atributos selecionados
attr =['C006','C008','I00102','J01101','Q046017','Q046015','Q046018','Q03802','Q02901','Q03002','Q03001','N001','N00101','N011','P00103','P00404','P00610','P00611','P02401','P02002','P018','P023','P027','P035','P05401','P052','P053','P050','P058','VDF004']
i = 0
#Drop dos atributos sem uso
while i < len(df.columns):
      if df.columns[i] not in attr:
            df = df.drop(df.columns[i], axis=1)
      else: i+=1
#Drop instancias duplicadas
df = df.drop_duplicates()
df

,C006,C008,I00102,J01101,N001,N00101,N011,P00103,P00404,P00610,...,P05401,P058,Q02901,Q03001,Q03002,Q03802,Q046015,Q046017,Q046018,VDF004
0,2.0,55.0,2.0,1.0,3.0,3.0,2.0,60.0,145.0,1.0,...,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0
1,1.0,69.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,1.0,31.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,1.0,9.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,2.0,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293718,1.0,54.0,1.0,1.0,3.0,3.0,1.0,89.0,168.0,2.0,...,NaN,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,5.0
293720,1.0,32.0,2.0,1.0,3.0,3.0,1.0,62.0,186.0,2.0,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
293722,1.0,84.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
293723,1.0,21.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
293724,2.0,13.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0

In [3]:
#Base filtrada para csv
df.to_csv('filtrada.csv')

In [4]:
# Base apenas com quem respondeu que recebeu diagnÃ³stico com Diabetes
mask = df['Q03001'] == 1.0
diab = df[mask]
# Base apenas com quem respondeu que nÃ£o recebeu diagnÃ³stico com Diabetes
mask2 = df['Q03001'] == 2.0
ndiab = df[mask2]

In [5]:
# Passando ambas para o csv
diab.to_csv('DIABETES.csv')
ndiab.to_csv('N_DIABETES.csv')

In [6]:
full=pd.concat([diab,ndiab], ignore_index=True, axis=0)
full

,C006,C008,I00102,J01101,N001,N00101,N011,P00103,P00404,P00610,...,P05401,P058,Q02901,Q03001,Q03002,Q03802,Q046015,Q046017,Q046018,VDF004
0,1.0,81.0,2.0,1.0,3.0,3.0,1.0,75.0,162.0,2.0,...,NaN,5.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,4.0
1,2.0,72.0,2.0,1.0,3.0,3.0,3.0,79.0,161.0,2.0,...,NaN,6.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,3.0
2,2.0,74.0,1.0,1.0,3.0,3.0,4.0,65.0,148.0,2.0,...,NaN,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,5.0
3,1.0,59.0,1.0,1.0,3.0,2.0,2.0,86.0,187.0,1.0,...,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,5.0
4,2.0,94.0,2.0,1.0,3.0,2.0,1.0,62.0,145.0,1.0,...,NaN,NaN,3.0,1.0,2.0,2.0,1.0,1.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84058,1.0,44.0,2.0,2.0,3.0,2.0,3.0,62.0,162.0,1.0,...,NaN,NaN,5.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0
84059,2.0,26.0,2.0,2.0,2.0,2.0,4.0,75.0,150.0,1.0,...,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0
84060,2.0,54.0,2.0,4.0,3.0,2.0,2.0,63.0,168.0,1.0,...,1.0,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0
84061,2.0,32.0,2.0,1.0,2.0,2.0,1.0,87.0,163.0,2.0,...,NaN,6.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0
84062,1.0,54.0,1.0,1.0,3.0,3.0,1.0,89.0,168.0,2.0,...,NaN,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,5.0

In [7]:
full.to_csv('Full_Diab_NDiab.csv', index=False)

In [8]:
imputer = KNNImputer(n_neighbors=2)
full_input = imputer.fit_transform(full)
full_input

array([[ 1. , 81. ,  2. , ...,  1. ,  1. ,  4. ],
       [ 2. , 72. ,  2. , ...,  1. ,  1. ,  3. ],
       [ 2. , 74. ,  1. , ...,  1. ,  1. ,  5. ],
       ...,
       [ 2. , 54. ,  2. , ...,  1. ,  1.5,  4. ],
       [ 2. , 32. ,  2. , ...,  1. ,  1.5,  2. ],
       [ 1. , 54. ,  1. , ...,  1. ,  1. ,  5. ]])

In [9]:
full_input = pd.DataFrame(full_input)
full_input.to_csv('inputed.csv', index=False)
full_input

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.0,81.0,2.0,1.0,3.0,3.0,1.0,75.0,162.0,2.0,...,5.0,5.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,4.0
1,2.0,72.0,2.0,1.0,3.0,3.0,3.0,79.0,161.0,2.0,...,1.0,6.0,1.0,1.0,2.0,2.0,1.5,1.0,1.0,3.0
2,2.0,74.0,1.0,1.0,3.0,3.0,4.0,65.0,148.0,2.0,...,5.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,5.0
3,1.0,59.0,1.0,1.0,3.0,2.0,2.0,86.0,187.0,1.0,...,3.0,1.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,5.0
4,2.0,94.0,2.0,1.0,3.0,2.0,1.0,62.0,145.0,1.0,...,5.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84058,1.0,44.0,2.0,2.0,3.0,2.0,3.0,62.0,162.0,1.0,...,1.0,1.0,5.0,2.0,1.5,1.5,1.0,1.0,1.5,2.0
84059,2.0,26.0,2.0,2.0,2.0,2.0,4.0,75.0,150.0,1.0,...,3.0,3.0,2.0,2.0,1.5,1.5,1.0,1.0,1.5,1.0
84060,2.0,54.0,2.0,4.0,3.0,2.0,2.0,63.0,168.0,1.0,...,1.0,1.0,3.0,2.0,1.5,1.5,1.0,1.0,1.5,4.0
84061,2.0,32.0,2.0,1.0,2.0,2.0,1.0,87.0,163.0,2.0,...,5.0,6.0,5.0,2.0,1.5,2.0,1.0,1.0,1.5,2.0
84062,1.0,54.0,1.0,1.0,3.0,3.0,1.0,89.0,168.0,2.0,...,1.0,1.0,3.0,2.0,2.0,2.0,1.5,1.0,1.0,5.0

In [11]:
full_input = pd.read_csv('inputed.csv', index_col=False)
z_scores = stats.zscore(full_input, nan_policy='omit')

# Define threshold (e.g., |Z| > 3)
threshold = 3

# Remove rows with outliers
df_no_outliers = full_input[(z_scores < threshold).all(axis=1)]
columns_mapping = dict(zip(df_no_outliers.columns, df.columns))
df_no_outliers.reset_index(drop=True, inplace=True)
df_no_outliers.rename(columns=columns_mapping, inplace=True)
df_no_outliers.to_csv('noOut.csv', index=False)
df_no_outliers

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_11752\3949525927.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers.rename(columns=columns_mapping, inplace=True)

,C006,C008,I00102,J01101,N001,N00101,N011,P00103,P00404,P00610,...,P05401,P058,Q02901,Q03001,Q03002,Q03802,Q046015,Q046017,Q046018,VDF004
0,1.0,81.0,2.0,1.0,3.0,3.0,1.0,75.0,162.0,2.0,...,5.0,5.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,4.0
1,2.0,72.0,2.0,1.0,3.0,3.0,3.0,79.0,161.0,2.0,...,1.0,6.0,1.0,1.0,2.0,2.0,1.5,1.0,1.0,3.0
2,1.0,59.0,1.0,1.0,3.0,2.0,2.0,86.0,187.0,1.0,...,3.0,1.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,5.0
3,2.0,94.0,2.0,1.0,3.0,2.0,1.0,62.0,145.0,1.0,...,5.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,4.0
4,2.0,30.0,2.0,1.0,2.0,1.0,1.0,55.0,175.0,2.0,...,1.5,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72049,2.0,51.0,2.0,1.0,4.0,3.0,4.0,62.0,158.0,2.0,...,3.0,1.0,3.0,2.0,2.0,2.0,1.5,1.0,1.5,4.0
72050,1.0,44.0,2.0,2.0,3.0,2.0,3.0,62.0,162.0,1.0,...,1.0,1.0,5.0,2.0,1.5,1.5,1.0,1.0,1.5,2.0
72051,2.0,26.0,2.0,2.0,2.0,2.0,4.0,75.0,150.0,1.0,...,3.0,3.0,2.0,2.0,1.5,1.5,1.0,1.0,1.5,1.0
72052,2.0,32.0,2.0,1.0,2.0,2.0,1.0,87.0,163.0,2.0,...,5.0,6.0,5.0,2.0,1.5,2.0,1.0,1.0,1.5,2.0
72053,1.0,54.0,1.0,1.0,3.0,3.0,1.0,89.0,168.0,2.0,...,1.0,1.0,3.0,2.0,2.0,2.0,1.5,1.0,1.0,5.0